#! /usr/bin/perl -w
#
# usage: 
#    check_rlm -F license_file
#
# Check available rlm license managers.
# Use lmstat to check the status of the license server
# described by the license file given as argument.
# Check and interpret the output of lmstat
# and create returncodes and output.
#
# Contrary to the nagios concept, this script takes
# a file, not a hostname as an argument and returns
# the status of hosts and services described in that
# file. Use these hosts.cfg entries as an example
#
#
# Notes:
# - you need the rlmstat utility which comes with rlm.
# - set the correct path in the variable $rlmstat.
#
# License: GPL
#
# initial version: 9-10-99 Ernst-Dieter Martin edmt@infineon.com
#
# lmstat output patches from Steve Rigler/Cliff Rice 13-Apr-2002
# srigler@marathonoil.com,cerice@marathonoil.com
# flexlm -> rlm   10-Jul-2012 Austin Murphy austin.murphy@gmail.com



use strict;
use Getopt::Long;
use vars qw($opt_V $opt_h $opt_F $opt_t $verbose $PROGNAME);
use lib "/usr/lib/nagios/plugins";
use utils qw(%ERRORS &print_revision &support &usage);

$PROGNAME="check_rlm";

sub print_help ();
sub print_usage ();

$ENV{'PATH'}='';
$ENV{'BASH_ENV'}=''; 
$ENV{'ENV'}='';

Getopt::Long::Configure('bundling');
GetOptions
	("V"   => \$opt_V,   "version"    => \$opt_V,
	 "h"   => \$opt_h,   "help"       => \$opt_h,
	 "v"   => \$verbose, "verbose"    => \$verbose,
	 "F=s" => \$opt_F,   "filename=s" => \$opt_F,
	 "t=i" => \$opt_t, "timeout=i"  => \$opt_t);

if ($opt_V) {
	print_revision($PROGNAME,'1.4.15');
	exit $ERRORS{'OK'};
}

unless (defined $opt_t) {
	$opt_t = $utils::TIMEOUT ;	# default timeout
}


if ($opt_h) {print_help(); exit $ERRORS{'OK'};}

unless (defined $opt_F) {
	print "Missing license.dat file\n";
	print_usage();
	exit $ERRORS{'UNKNOWN'};
}
# Just in case of problems, let's not hang Nagios
$SIG{'ALRM'} = sub {
	print "Timeout: No Answer from Client\n";
	exit $ERRORS{'UNKNOWN'};
};
alarm($opt_t);

#my $lmstat = $utils::PATH_TO_LMSTAT ;
my $lmstat = "/usr/local/bin/rlmstat" ;
unless (-x $lmstat ) {
	print "Cannot find \"rlmstat\"\n";
	exit $ERRORS{'UNKNOWN'};
}

($opt_F) || ($opt_F = shift) || usage("License file not specified\n");
my $licfile = $1 if ($opt_F =~ /^(.*)$/);
($licfile) || usage("Invalid filename: $opt_F\n");

print "$licfile\n" if $verbose;

if ( ! open(CMD,"$lmstat -c $licfile |") ) {
	print "ERROR: Could not open \"$lmstat -c $licfile\" ($!)\n";
	exit exit $ERRORS{'UNKNOWN'};
}

my $serverup = 0;
my @upsrv; 
my @uptimes; 
my @downsrv;  # list of servers up and down

 
# key off of the term "license server" and 
# grab the status.  Keep going until "Vendor" is found
#

#
# Collect list of license servers by their status
# Vendor daemon status is ignored for the moment.

while ( <CMD> ) {
	next if (/^rlmstat/);   # ignore 1st line - util info
	next if (/^Copyright/); # ignore 2nd line - copyright
	(/ISV servers/) && last;   # ignore Vendor daemon status
	print $_ if $verbose;
	
		if ($_ =~ /rlm status on/) {	# matched 1 (of possibly 3) license server
			s/^\s*//;					#some servers start at col 1, other have whitespace
										# strip staring whitespace if any
			if ( $_ =~ /up/) {
				$_ =~ /^\s*rlm status on (.*) \(port \d+\), up (.*)$/ ;
				push(@upsrv, $1);
				push(@uptimes, $2);
				print "up:$1:\n" if $verbose;
			} else {
				$_ =~ /^(.*):/; 
				push(@downsrv, $1);
				print "down:$1:\n" if $verbose;
			}
		
		}

}


close CMD;

if ($verbose) {
	print "License Servers running: ".scalar(@upsrv) ."\n";
	foreach my $upserver (@upsrv) {
		print "$upserver\n";
	}
	print "License servers not running: ".scalar(@downsrv)."\n";
	foreach my $downserver (@downsrv) {
		print "$downserver\n";
	}
}


my $comment;
#
# print list of servers which are up. 
#
if (scalar(@upsrv) > 0) {
   $comment .= "License Servers running: ";
   foreach my $upserver (@upsrv) {
      $comment .= "$upserver,";
   }
}
#
# Ditto for those which are down.
#
if (scalar(@downsrv) > 0) {
   $comment .= "License servers NOT running: ";
   foreach my $downserver (@downsrv) {
      $comment .= "$downserver,";
   }
}

# perfdata
my $perfdata;
#print "\n|rlm::up:".scalar(@upsrv).";down:".scalar(@downsrv)."\n";
$perfdata .= "|rlm::up:".scalar(@upsrv).";uptime: ";
foreach my $ut (@uptimes) {
  $perfdata .= "$ut, ";
}
$perfdata .= ";down:".scalar(@downsrv)."\n";


$comment =~ s/,\s*$//;

if ( scalar(@downsrv) == 0 ) {
    print "RLM OK - $comment \n";
    # maybe print perfdata ?
    exit $ERRORS{'OK'} ;
} elsif ( (scalar(@upsrv) > 0) && (scalar(@downsrv) > 0)) {
    print "RLM WARNING - $comment \n";
    exit $ERRORS{'WARNING'} ;
} else {
    print "RLM CRITICAL - $comment \n";
    exit $ERRORS{'CRITICAL'} ;
}




sub print_usage () {
	print "Usage:
   $PROGNAME -F <filename> [-v] [-t] [-V] [-h]
   $PROGNAME --help
   $PROGNAME --version
";
}

sub print_help () {
	print_revision($PROGNAME,'1.4.16');
	print "Copyright (c) 2000 Ernst-Dieter Martin/Karl DeBisschop

Check available rlm license managers

";
	print_usage();
	print "
-F, --filename=FILE
   Name of license file (usually \"license.dat\")
-v, --verbose
   Print some extra debugging information (not advised for normal operation)
-t, --timeout
   Plugin time out in seconds (default = $utils::TIMEOUT )
-V, --version
   Show version and license information
-h, --help
   Show this help screen

rlm license managers usually run as a single server
  The plugin returns OK if 1 (single) or 3 (triple) servers
are running, CRITICAL if 1(single) or 3 (triple) servers are down, and WARNING
if 1 or 2 of 3 servers are running\n
";
	support();
}
